export default function Home() {
    return (
        <main
              style={{
                      minHeight: "100vh",
                              background: "#eef4ff",
                                      padding: "20px",
                                              fontFamily: "Arial",
                                                    }}
                                                        >
                                                              <div
                                                                      style={{
                                                                                maxWidth: "450px",
                                                                                          margin: "auto",
                                                                                                    background: "white",
                                                                                                              padding: "20px",
                                                                                                                        borderRadius: "15px",
                                                                                                                                  boxShadow: "0 0 10px rgba(0,0,0,0.1)",
                                                                                                                                          }}
                                                                                                                                                >
                                                                                                                                                        <h1
                                                                                                                                                                  style={{
                                                                                                                                                                              textAlign: "center",
                                                                                                                                                                                          color: "#0066ff",
                                                                                                                                                                                                      marginBottom: "20px",
                                                                                                                                                                                                                }}
                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                  🚖 Vishwakarma Travels
                                                                                                                                                                                                                                          </h1>

                                                                                                                                                                                                                                                  <input placeholder="Customer Name" style={inputStyle} />
                                                                                                                                                                                                                                                          <input placeholder="Mobile Number" style={inputStyle} />
                                                                                                                                                                                                                                                                  <input placeholder="Pickup Location" style={inputStyle} />
                                                                                                                                                                                                                                                                          <input placeholder="Drop Location" style={inputStyle} />

                                                                                                                                                                                                                                                                                  <input type="date" style={inputStyle} />

                                                                                                                                                                                                                                                                                          <select style={inputStyle}>
                                                                                                                                                                                                                                                                                                    <option>Select Vehicle</option>
                                                                                                                                                                                                                                                                                                              <option>Sedan</option>
                                                                                                                                                                                                                                                                                                                        <option>SUV</option>
                                                                                                                                                                                                                                                                                                                                  <option>Innova</option>
                                                                                                                                                                                                                                                                                                                                          </select>

                                                                                                                                                                                                                                                                                                                                                  <button style={buttonStyle}>
                                                                                                                                                                                                                                                                                                                                                            Submit Booking
                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                const inputStyle = {
                                                                                                                                                                                                                                                                                                                                                                                  width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                    padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                      marginBottom: "12px",
                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                          border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                          const buttonStyle = {
                                                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                              padding: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                background: "#0066ff",
                                                                                                                                                                                                                                                                                                                                                                                                  color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                    border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                        };
}