"use client";
import { useEffect } from "react";

const hide=(e:HTMLInputElement|HTMLSelectElement)=>{e.style.setProperty("display","none","important");e.style.setProperty("position","absolute","important");e.style.setProperty("left","-9999px","important")};
const setVal=(i:HTMLInputElement,v:string)=>{Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,"value")?.set?.call(i,v);i.dispatchEvent(new Event("input",{bubbles:true}));i.dispatchEvent(new Event("change",{bubbles:true}))};
const time12=(v:string)=>!v?"Select Time":/am|pm/i.test(v)?v:new Date(`2000-01-01T${v}`).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",hour12:true});
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const nice=(v:string)=>v?new Date(`${v}T00:00:00`).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"Select Date";
const close=()=>document.querySelectorAll(".open").forEach(e=>e.classList.remove("open"));

function label(s:HTMLSelectElement,i:number){const o=Array.from(s.options).map(x=>x.text);if(o.includes("Mr."))return"Select Gender";if(o.includes("Sedan"))return"Select Vehicle Type";if(o.includes("Desire"))return"Select Vehicle Model";if(o.includes("One Way Drop Pickup"))return"Select Service";return`Select Option ${i+1}`}
function customSelect(s:HTMLSelectElement,i:number){if(s.dataset.customDropdownReady==="yes")return hide(s);s.dataset.customDropdownReady="yes";const w=document.createElement("div"),b=document.createElement("button"),m=document.createElement("div");w.className="vt-custom-select";b.type="button";b.className="vt-custom-select-btn";m.className="vt-custom-select-menu";const txt=()=>b.innerHTML=`<span>${s.options[s.selectedIndex]?.text||label(s,i)}</span><b>⌄</b>`;txt();Array.from(s.options).forEach(o=>{const it=document.createElement("button");it.type="button";it.className="vt-custom-select-item";it.textContent=o.text;it.onclick=e=>{e.stopPropagation();s.value=o.value;s.dispatchEvent(new Event("change",{bubbles:true}));txt();w.classList.remove("open")};m.appendChild(it)});b.onclick=e=>{e.stopPropagation();close();w.classList.toggle("open")};w.append(b,m);s.parentElement?.insertBefore(w,s);hide(s)}
function datePicker(i:HTMLInputElement){if(i.dataset.customPickerReady==="yes")return hide(i);i.dataset.customPickerReady="yes";const w=document.createElement("div"),b=document.createElement("button"),m=document.createElement("div");w.className="vt-picker";b.type="button";b.className="vt-custom-select-btn";m.className="vt-picker-menu";const txt=()=>b.innerHTML=`<span>📅 ${nice(i.value)}</span><b>⌄</b>`;txt();for(let n=0;n<14;n++){const d=new Date();d.setDate(d.getDate()+n);const v=iso(d),it=document.createElement("button");it.type="button";it.className="vt-custom-select-item";it.textContent=d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",weekday:"short"});it.onclick=e=>{e.stopPropagation();setVal(i,v);txt();close()};m.appendChild(it)}b.onclick=e=>{e.stopPropagation();close();w.classList.toggle("open")};w.append(b,m);i.parentElement?.insertBefore(w,i);hide(i)}
function timePicker(i:HTMLInputElement){if(i.dataset.customPickerReady==="yes")return hide(i);i.dataset.customPickerReady="yes";const w=document.createElement("div"),b=document.createElement("button"),m=document.createElement("div");w.className="vt-picker vt-time-picker";b.type="button";b.className="vt-custom-select-btn";m.className="vt-time-menu";m.innerHTML='<div class="vt-time-head"><b>🕘 Select Time</b><button type="button" class="vt-time-close">×</button></div><div class="vt-time-grid"></div><div class="vt-custom-row"><span>Custom</span><select class="vt-h"></select><select class="vt-m"></select><select class="vt-ap"><option>AM</option><option>PM</option></select><button type="button">Done</button></div>';const txt=()=>b.innerHTML=`<span>🕘 ${time12(i.value)}</span><b>⌄</b>`;txt();const g=m.querySelector(".vt-time-grid") as HTMLDivElement;Array.from({length:30},(_,n)=>{const h=7+Math.floor(n/2),mm=n%2?30:0,ap=h>=12?"PM":"AM",hh=h%12||12,t=`${String(hh).padStart(2,"0")}:${String(mm).padStart(2,"0")} ${ap}`;return{t}}).forEach(({t})=>{const it=document.createElement("button");it.type="button";it.className="vt-time-slot";it.textContent=t;it.onclick=e=>{e.stopPropagation();setVal(i,t);txt();close()};g.appendChild(it)});const hs=m.querySelector(".vt-h") as HTMLSelectElement,ms=m.querySelector(".vt-m") as HTMLSelectElement,ap=m.querySelector(".vt-ap") as HTMLSelectElement;for(let n=1;n<=12;n++)hs.add(new Option(String(n).padStart(2,"0")));for(let n=0;n<60;n++)ms.add(new Option(String(n).padStart(2,"0")));hs.value="07";ms.value="40";m.querySelector(".vt-time-close")?.addEventListener("click",e=>{e.stopPropagation();close()});m.querySelector(".vt-custom-row button")?.addEventListener("click",e=>{e.stopPropagation();setVal(i,`${hs.value}:${ms.value} ${ap.value}`);txt();close()});b.onclick=e=>{e.stopPropagation();close();w.classList.toggle("open")};w.append(b,m);i.parentElement?.insertBefore(w,i);hide(i)}
export default function AdminCustomDropdowns(){useEffect(()=>{const setup=()=>{document.querySelectorAll<HTMLSelectElement>(".admin-shell form select:not(.vt-ap):not(.vt-h):not(.vt-m)").forEach(customSelect);const d=document.querySelector<HTMLInputElement>('.admin-shell form input[type="date"]');if(d)datePicker(d);const t=Array.from(document.querySelectorAll<HTMLInputElement>(".admin-shell form input")).find(x=>(x.placeholder||"").toLowerCase().includes("time"));if(t)timePicker(t)};setup();const int=window.setInterval(setup,800);const obs=new MutationObserver(setup);obs.observe(document.body,{childList:true,subtree:true});document.addEventListener("click",close);return()=>{window.clearInterval(int);obs.disconnect();document.removeEventListener("click",close)}},[]);return null}
